module.exports = Object.freeze({
    AVAA_RAPORTTI: "EVENT_AVAA_RAPORTTI",
    RAPORTTI_VALITTU: "EVENT_RAPORTTI_VALITTU",
    RAPORTIT_UPDATE: "EVENT_RAPORTIT_UPDATE",
    LOGOUT: "EVENT_LOGOUT",
    SAVE_EMAIL: "EVENT_SAVE_EMAIL",
    EMAIL_SAVED: "EVENT_EMAIL_SAVED",
    REQUEST_LINK: "EVENT_REQUEST_LINK",
    CHANGE: "EVENT_CHANGE",
    CLOSE_REPORT: "EVENT_CLOSE_REPORT",
    DATE_FILTER: "EVENT_DATE_FILTER",
    USER_FILTER: "EVENT_USER_FILTER",
    DOWNLOAD: "EVENT_DOWNLOAD",
});